config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: "cocktails#index"
  resources :cocktails, only: [:create, :index, :show, :new] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail, scope: [:ingredient]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def index
    @doses = Dose.all
  end

  def show
    @doses = Dose.find(params[:id])
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
  <%= render 'shared/banner' %>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>

      <div class="col-sm-12 col-md-4">
        <%= render 'shared/card', cocktail: cocktail %>
      </div>

    <% end %>
  </div>

</div>
  <%= render 'shared/footer' %>

app/views/cocktails/new.html.erb
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.submit "add a cocktail", class: "btn btn-primary" %>
<% end %>
<%= link_to "retour", cocktails_path, class: "btn btn-primary" %>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>
  <% @cocktail.doses.each do|dose| %>
  <h2><%= "#{dose.description} de #{dose.ingredient.name}" %></h2>
  <% end %>



  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.error_notification %>

    <%= f.input :description %>
    <%= f.association :ingredient %>

    <%= f.button :submit, class: "btn-primary" %>
  <% end %>

  <%= link_to "retour", cocktails_path, class: "btn btn-primary" %>
</div>

app/views/doses/index.hmtl.erb
<% @doses.each do |dose| %>
  <h2><%= dose.name %></h2>
<% end %>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.submit "add a dose", class: "btn btn-primary" %>

<% end %>

app/views/doses/show.html.erb
<h2><%= @dose.name %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- render navbar here   -->
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://vranken.net/wp-content/uploads/2018/04/cocktails-pour-les-f%C3%AAtes.jpg);">
  <div class="container">
    <h1>LA KINTE À TINMAR, LE MEILLEUR DU PIRE POUR SE METTRE UNE TAULE!</h1>
    <!-- <a class="btn btn-flat" href="#">Apply now</a> -->
  </div>
</div>

app/views/shared/_button.html.erb
<div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Yay!</strong> 🎉 you successfully signed in to our service.</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

<div class="flash flash-warning alert alert-dismissible fade show" role="alert">
  <span><strong>Mmh</strong> 🤔 seems like you don't have <a href="#">profile picture</a> yet.</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

<div class="flash flash-danger alert alert-dismissible fade show" role="alert">
  <span><strong>Oops!</strong> 😱 a problem has occurred while processing your booking.</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

app/views/shared/_card.html.erb
<%= link_to cocktail_path(cocktail) do %>
<div class="card-trip m-3">
  <img src="http://gingerman.cafe/wp-content/uploads/2017/01/monaco.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2><%=cocktail.name%></h2>
      <!-- <p>Short description here!</p> -->
    </div>
    <!-- <h2 class="card-trip-pricing">£99.99</h2> -->
    <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> -->
  </div>
</div>
<%end%>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Au Wagon on <i class="fas fa-heart"></i> les Cocktails
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to  cocktails_path, class: "navbar-brand" do %>
    <img src="https://i.pinimg.com/236x/5a/58/d3/5a58d318ce08605d538626269e5cadf6.jpg" />
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active btn btn-primary">
        <a href="/cocktails/new">Ajouter un cocktail</a>
      </li>
    </ul>
  </div>
</div>